### ISSUE TITLE
[Permission] Repo 에 push 할 권한이 없습니다.

### ISSUE THREAD

**Issue by erados** [drum-grammer/docker-pro-2308#12]
readme 의 [방법2](https://github.com/drum-grammer/docker-pro-2308#%EB%B0%A9%EB%B2%95-2) 를 사용하려는데 push 권한이 부족한 듯 합니다. 

권한을 추가 부탁드립니다.

```
ERROR: Permission to drum-grammer/docker-pro-2308.git denied to erados.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by drum-grammer** [comment]
네 collaborators로 초대 하였습니다. 🙏
<img width="1037" alt="image" src="https://github.com/drum-grammer/docker-pro-2308/assets/48014144/862a6d00-ce0f-4814-aef8-a8636060a970">

**Comment by new-h2** [comment]
안녕하세요 저도 권한 추가요청드립니다! 

ERROR: Permission to drum-grammer/docker-pro-2308.git denied to new-h2.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by drum-grammer** [comment]
네 위 두분도 collaborators로 초대 하였습니다. 🙏

**Comment by techhan** [comment]
안녕하세요. 저도 초대 부탁드립니다.

**Comment by drum-grammer** [comment]
<img width="965" alt="image" src="https://github.com/drum-grammer/docker-pro-2308/assets/48014144/51b9d221-42fd-4a3d-8ceb-4a751dcc6f94">

네 추가로 초대해드렸습니다. 🙏

**Comment by kimx3966** [comment]
저도 추가해주시면 감사하겠습니다.

**Comment by drum-grammer** [comment]
![image](https://github.com/drum-grammer/docker-pro-2308/assets/48014144/d3c2c4dc-1552-4712-99a5-48a557191066)

이상 신청하신 분 모두 collaborator로 초대 드렸습니다.
